name: ${PROJECT_NAME}-Docker-Selfhosted

on:
  workflow_dispatch:
    inputs:
      build_amd64:
        description: 'Build for amd64'
        type: boolean
        default: true
      build_arm64:
        description: 'Build for arm64/v8'
        type: boolean
        default: false
      build_386:
        description: 'Build for 386'
        type: boolean
        default: false
      build_skip:
        description: 'Skip build (for testing)'
        type: boolean
        default: false
      build_force:
        description: 'Force build (for testing)'
        type: boolean
        default: false
      release_skip:
        description: 'Skip release (for testing)'
        type: boolean
        default: false

  push:
    paths:
      - '.github/workflows/${PROJECT_NAME}-Docker-Selfhosted.yml'
      - '${CUSTOM_FILES_GLOB}'
    branches: [ main, test ]

  schedule:
    - cron: '${CRON_SCHEDULE}'

env:
  PROJECT_NAME: ${PROJECT_NAME}
  REPO_EXT_URL: ${REPO_EXT_URL}
  REPO_EXT_NAME: ${REPO_EXT_NAME}
  DOCKER_REPO: ${DOCKER_REPO}
  WORKDIR: ${WORKDIR}
  TAR_DIR: ${TAR_DIR}
  ARTIFACT_DIR: ${ARTIFACT_DIR}
  CUSTOM_DOCKERFILE: ${CUSTOM_DOCKERFILE}
  CUSTOM_ENTRYPOINT: ${CUSTOM_ENTRYPOINT}
  CUSTOM_INIT: ${CUSTOM_INIT}

jobs:
  prepare:
    runs-on: self-hosted
    outputs:
      repo_tag:     ${{ steps.meta.outputs.repo_tag }}
      combined_tag: ${{ steps.meta.outputs.combined_tag }}
      skip:         ${{ steps.meta.outputs.skip }}
    steps:
      - name: 🧹 Clean workspace
        run: sudo find . -mindepth 1 -delete

      - name: 🌐 Install dependencies
        run: |
          sudo timedatectl set-timezone Europe/Moscow
          sudo apt-get update && sudo apt-get install -y jq curl tree

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: 📦 Fetch latest upstream tag
        id: meta
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/${{ env.REPO_EXT_NAME }}/releases/latest | jq -r '.tag_name')
          combined="${{ env.PROJECT_NAME }}_${latest_tag}"

          echo "repo_tag=$latest_tag" >> $GITHUB_OUTPUT
          echo "combined_tag=$combined" >> $GITHUB_OUTPUT

          skip=false
          if git rev-parse "refs/tags/$combined" >/dev/null 2>&1; then skip=true; fi
          if [ "${{ github.event.inputs.build_force }}" = "true" ]; then skip=false; fi
          if [ "${{ github.event.inputs.build_skip }}" = "true" ]; then skip=true; fi

          echo "skip=$skip" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    if: ${{ needs.prepare.outputs.skip == 'false' && github.event.inputs.build_skip == 'false' }}
    runs-on: self-hosted
    outputs:
      repo_tag:  ${{ needs.prepare.outputs.repo_tag }}
      platforms: ${{ steps.platforms.outputs.platforms }}
      skip:      ${{ needs.prepare.outputs.skip }}
    steps:
      - name: 🬸 Compose selected platforms
        id: platforms
        run: |
          platforms=""
          [ "${{ github.event.inputs.build_amd64 }}" = "true" ] && platforms="${platforms},linux/amd64"
          [ "${{ github.event.inputs.build_arm64 }}" = "true" ] && platforms="${platforms},linux/arm64/v8"
          [ "${{ github.event.inputs.build_386 }}" = "true" ] && platforms="${platforms},linux/386"
          platforms="${platforms#,}"
          echo "platforms=$platforms" >> $GITHUB_OUTPUT

      - name: 🔧 Clone external repo
        run: |
          git clone ${{ env.REPO_EXT_URL }} ${{ env.WORKDIR }}
          cd ${{ env.WORKDIR }}
          git checkout ${{ needs.prepare.outputs.repo_tag }}

      - name: ⚙️ Prepare folders
        run: |
          mkdir -p ${{ env.ARTIFACT_DIR }} ${{ env.TAR_DIR }}
          echo "${{ steps.platforms.outputs.platforms }}" > "${{ env.ARTIFACT_DIR }}/platforms.txt"
          echo "${{ needs.prepare.outputs.repo_tag }}"    > "${{ env.ARTIFACT_DIR }}/repo_tag.txt"

      - name: 🛠️ Copy Docker files
        run: |
          [ -f "${{ env.CUSTOM_DOCKERFILE }}" ] && cp "${{ env.CUSTOM_DOCKERFILE }}" "${{ env.WORKDIR }}/Dockerfile"
          [ -f "${{ env.CUSTOM_ENTRYPOINT }}" ] && cp "${{ env.CUSTOM_ENTRYPOINT }}" "${{ env.WORKDIR }}/DockerEntrypoint.sh"
          [ -f "${{ env.CUSTOM_INIT }}" ]       && cp "${{ env.CUSTOM_INIT }}"       "${{ env.WORKDIR }}/DockerInit.sh"
          test -f "${{ env.WORKDIR }}/Dockerfile" || { echo "❌ Dockerfile missing"; exit 1; }

      - name: 🧱 Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 DockerHub Login (retry)
        run: |
          for i in {1..5}; do
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin && break
            sleep 5
          done

      - name: ⚙️ Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: 🏗️ Build & Push
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ env.WORKDIR }}
          platforms: ${{ steps.platforms.outputs.platforms }}
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:latest
            ${{ env.DOCKER_REPO }}:${{ needs.prepare.outputs.repo_tag }}
          cache-from: |
            type=registry,ref=${{ env.DOCKER_REPO }}:buildcache
          cache-to: |
            type=registry,ref=${{ env.DOCKER_REPO }}:buildcache,mode=max

  release:
    needs: build
    if: ${{ needs.build.outputs.skip == 'false' && github.event.inputs.release_skip == 'false' }}
    runs-on: self-hosted
    steps:
      - name: 📦 Save & Compress Docker Image
        run: |
          mkdir -p "${{ env.TAR_DIR }}/latest"
          docker pull "${{ env.DOCKER_REPO }}:latest"
          docker save -o "${{ env.TAR_DIR }}/latest/image.tar" "${{ env.DOCKER_REPO }}:latest"
          tar -czf "${{ env.TAR_DIR }}/${{ env.PROJECT_NAME }}-latest.tar.gz" -C "${{ env.TAR_DIR }}/latest" .
          rm -rf "${{ env.TAR_DIR }}/latest"

      - name: 📋 Generate Platform Markdown
        id: platforms-md
        run: |
          list=""
          IFS=',' read -ra ARGS <<< "${{ needs.build.outputs.platforms }}"
          for p in "${ARGS[@]}"; do
            safe=$(echo "$p" | sed 's#/#-#g')
            list+="- \`$p\` → [DockerHub](https://hub.docker.com/r/${{ env.DOCKER_REPO }}/tags?name=$safe)\n"
          done
          echo "platforms_list<<EOF" >> $GITHUB_OUTPUT
          echo -e "$list" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: 🚀 Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.PROJECT_NAME }}_${{ needs.build.outputs.repo_tag }}
          name: "${{ env.PROJECT_NAME }} Release ${{ needs.build.outputs.repo_tag }}"
          token: ${{ secrets.GIT_TOKEN }}
          prerelease: false
          body: |
            ### 📦 Release Info
            - ![](https://img.shields.io/docker/pulls/${{ env.DOCKER_REPO }}.svg?style=flat-square)
            - Pull: `docker pull ${{ env.DOCKER_REPO }}:latest`
            - Platforms:
            ${{ steps.platforms-md.outputs.platforms_list }}
          files: |
            ${{ env.TAR_DIR }}/*.tar.gz
