name: Caddy-L4-Docker-SelfHosted

on:
  workflow_dispatch:
    inputs:
      build_amd64:
        description: Build linux/amd64
        required: false
        default: true
        type: boolean
      build_arm64:
        description: Build linux/arm64/v8
        required: false
        default: false
        type: boolean
      build_386:
        description: Ignored for Caddy-L4 because linux/386 is unsupported
        required: false
        default: false
        type: boolean
      build_skip:
        description: Skip build
        required: false
        default: false
        type: boolean
      build_force:
        description: Force build even if release exists
        required: false
        default: false
        type: boolean
      release_skip:
        description: Skip GitHub release creation
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      build_amd64:
        required: false
        default: true
        type: boolean
      build_arm64:
        required: false
        default: false
        type: boolean
      build_386:
        required: false
        default: false
        type: boolean
      build_skip:
        required: false
        default: false
        type: boolean
      build_force:
        required: false
        default: false
        type: boolean
      release_skip:
        required: false
        default: false
        type: boolean
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

permissions:
  contents: write
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  docker:
    uses: ./.github/workflows/_docker-project-build.yml
    with:
      project_name: Caddy-L4
      release_tag_prefix: Caddy-L4
      release_name_prefix: Caddy-L4
      artifact_prefix: caddy-l4
      repo_ext_name: caddyserver/caddy
      docker_repo: torotin/caddy-l4
      prepare_mode: in-repo-context
      workdir: .
      custom_dockerfile: ./bin/caddy/dockerfile
      custom_entrypoint: ./bin/caddy/DockerEntrypoint.sh
      default_platforms: linux/amd64
      supported_platforms: linux/amd64,linux/arm64/v8
      build_amd64: ${{ inputs.build_amd64 }}
      build_arm64: ${{ inputs.build_arm64 }}
      build_386: ${{ inputs.build_386 }}
      build_skip: ${{ inputs.build_skip }}
      build_force: ${{ inputs.build_force }}
      release_skip: ${{ inputs.release_skip }}
    secrets: inherit
