name: usque-Docker-SelfHosted

on:
  workflow_dispatch:
    inputs:
      build_amd64:
        description: Build linux/amd64
        required: false
        default: true
        type: boolean
      build_arm64:
        description: Build linux/arm64/v8
        required: false
        default: false
        type: boolean
      build_386:
        description: Build linux/386
        required: false
        default: false
        type: boolean
      build_skip:
        description: Skip build
        required: false
        default: false
        type: boolean
      build_force:
        description: Force build even if release exists
        required: false
        default: false
        type: boolean
      recreate_release:
        description: Delete existing GitHub Release before creating a new one
        required: false
        default: false
        type: boolean
      release_skip:
        description: Skip GitHub release creation
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      build_amd64:
        required: false
        default: true
        type: boolean
      build_arm64:
        required: false
        default: false
        type: boolean
      build_386:
        required: false
        default: false
        type: boolean
      build_skip:
        required: false
        default: false
        type: boolean
      build_force:
        required: false
        default: false
        type: boolean
      recreate_release:
        required: false
        default: false
        type: boolean
      release_skip:
        required: false
        default: false
        type: boolean
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

permissions:
  contents: write
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  docker:
    uses: ./.github/workflows/_docker-project-build.yml
    with:
      project_name: usque
      release_tag_prefix: usque
      release_name_prefix: usque
      artifact_prefix: usque
      repo_ext_url: https://github.com/Diniboy1123/usque.git
      repo_ext_name: Diniboy1123/usque
      docker_repo: torotin/usque
      prepare_mode: clone-release
      workdir: ./WORKDIR
      custom_dockerfile: ./bin/usque/Dockerfile
      custom_entrypoint: ./bin/usque/DockerEntrypoint.sh
      custom_init: ./bin/usque/DockerInit.sh
      default_platforms: linux/amd64,linux/386
      supported_platforms: linux/amd64,linux/arm64/v8,linux/386
      build_amd64: ${{ inputs.build_amd64 }}
      build_arm64: ${{ inputs.build_arm64 }}
      build_386: ${{ inputs.build_386 }}
      build_skip: ${{ inputs.build_skip }}
      build_force: ${{ inputs.build_force }}
      recreate_release: ${{ inputs.recreate_release }}
      release_skip: ${{ inputs.release_skip }}
    secrets: inherit
